name: Update

on:
  schedule:
    - cron: "51 5 12 * *" # At 05:51 on 12th day-of-month
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Python set up
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
          # pre-commit has its own cache
          # cache: "pip"

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit autoupdate
        run: |
          pre-commit autoupdate

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Commit changes if any
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git add .pre-commit-config.yaml
            git commit -m "Update .pre-commit-config.yaml" || true
            git push
          fi
